### ISSUE TITLE
7. Conversation Flow Screen

### ISSUE THREAD

**Issue by ChakshuGautam** [Samagra-Development/UCI-Console#3]
**Description** - Create a generic UI component for adding conversation logic, chaining of multiple logics.

**Outcome**
- Ability to add Conversation Logic (currently, only ODK) with metadata 
- Ability to chain multiple `Conversation Logics` - visible in a tabular format in the UI

**Success Metrics**
- Successfully add Conversation Logic and launch Bot
- Add, edit, delete Conversation Logics from the tabular UI

**Functional Requirements**
1. Click on 'Add Logic' to add new conversation logic
- Provide conversation logic metadata - Name and Description 
- Upload ODK form (.xml)
- Click on 'Add' to add conversation logic to tabular UI
- Cancel to go back to Conversation logic screen
2. Edit/Delete conversation logics in tabular UI 
3. Save bot as a draft, or launch it.
4. Checkbox to agree to terms and conditions
5. Cancel to go back to Conversation setup screen

**Non-Functional Requirements**
Telemetry: Instrumentation should help find out -
a) In a day, how many users (unique and total) are visiting the conversation flow screen
b) In a day, how many users (unique and total) are clicking on 'Add Logic' button
c) In a day, how many ODK forms are being uploaded
d) In a day, how many users (unique and total) are clicking on 'Save' button
e) In a day, how many users (unique and total) are clicking on 'Submit' button
f) In a day, how many users (unique and total) are clicking on 'Cancel' button

**Additional Dependencies on other Components**
The metadata to be provided for each transformer must be the same fields as present in the config object of the transformer definition. For instance, for the ODK transformer, the configuration definition should be the following:
```
{
	"name": "SamagraODKAgg",
	"tags": [
		"ODK"
	],
	"config": {
	  "fields": [
            { "name": "formID", type: "string", "required": false},
            { "name": "form", type: "file", required: false},
           },
	"id": "bbf56981-b8c9-40e9-8067-468c2c753659",
	"service_id": "94b7c56a-6537-49e3-88e5-4ea548b2f075",
	"service": {
		...
	}
}
```
- Dependent on uniform transformer metadata definition which can enable the creation of a generic UI component for transformer meta addition

**Links**
Wireframes - 
![7  Conversation flow empty state@2x_Updated](https://user-images.githubusercontent.com/80503666/121385390-b24a6800-c966-11eb-9a7e-4d4444b82209.jpg)
![8  Add logic popup@2x_Updated](https://user-images.githubusercontent.com/80503666/121385399-b4142b80-c966-11eb-9ec7-93d3f37fbc02.jpg)
![9  Conversation flow filled@2x_Updated](https://user-images.githubusercontent.com/80503666/121385405-b5455880-c966-11eb-96e6-459825e9084f.jpg)

APIs - [Link](https://www.postman.com/collections/437e7d1fc9f04ea2ce3e)

**Comment by aayushkedia95** [comment]
*Changes*

- [x] Image to be added (svg shared)
- [x] ODK Upload APIs
- [x] Description to be a text box
- [x] Popup blank space to be reduced
- [x] On adding logic, UI gets distorted - Add logic button
- [x] Submit disabled color - light blue
- [x] Remove multi-select from table
- [x] Check column width
- [x] Add Edit/Delete in action in table (Edit to popup - Delete to remove from table)

**Comment by aayushkedia95** [comment]
*Changes*

- [x] Text change - I agree to the required terms and conditions @manojSRawat
- [x] Popup on terms and conditions - https://diksha.gov.in/term-of-use.html (2 tabs) @manojSRawat
- [x] Save APIs @ChakshuGautam 
- [x] Popup size to be corrected @manojSRawat
- [x] Form Upload API to be bound @manojSRawat @ChakshuGautam 
- [x] Error handling + modal (Duplication in conversation name, starting message, conversation logic name, submitting without conversation logic) @manojSRawat
- [x] Steps > Step @manojSRawat
- [x] Edit - Change ‘Add’ to ‘Update’ @manojSRawat
- [x] Cancel > Back @manojSRawat
